spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages

  #liquibase
  liquibase.change-log: classpath:/db/changelog/db-changelog.xml

remote-server.url: http://localhost:8080