spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages

  #liquibase
  liquibase.change-log: classpath:/db/changelog/db-changelog.xml

  kafka:
    producer:
      properties:
        spring:
          json:
            add.type.headers: false

    consumer:
      properties:
        spring.json.trusted.packages: "*"
    admin:
      properties:
        min-in-sync-replicas: 2
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

  cloud:
    zookeeper:
      config.enabled: false
      connect-string: localhost:2181

app:
  group-id: server